name: build v8 9.4

on: 
  workflow_dispatch:
    inputs:
      tag_date:
        description: 'tag date'     
        required: true

#https://docs.google.com/document/d/1oFPHyNb_eXg6NzrE6xJDNPdJrHMZvx0LqsD6wpbd9vY/edit#heading=h.4tfb7x3beh2l
#libwee8按设计只支持wasm，不支持js，但8.4.371.19版本尚未移除js功能，还能用，如果升级v8版本要注意
#libmonolith会稳妥一些，但静态库大小会大些
env:
  VERSION: 9.4.146.24

jobs:
  build_android_arm_v8:
    name: Android (arm64-v8a)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        npm i
        sh ./android_armv8.sh ${{env.VERSION}}
        mv ~/v8/v8/output/v8 ~/v8/v8/output/v8_9.4
    - uses: actions/upload-artifact@v4
      with:
        name: v8_bin
        path: ~/v8/v8/output/**/*

  build_switch_arm_v8:
    name: Switch (arm64-v8a)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        npm i
        sh ./switch_armv8.sh ${{env.VERSION}}
        mv ~/v8/v8/output/v8 ~/v8/v8/output/v8_9.4
    - uses: actions/upload-artifact@v4
      with:
        name: v8_bin
        path: ~/v8/v8/output/**/*
        
  publish:
    runs-on: ubuntu-20.04
    needs: [build_android_arm_v8,build_switch_arm_v8]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: v8_bin
          path: v8_bin/
          
      - name: Create Release Asset
        run: |
          cd v8_bin/ && tar cvfz ../v8_bin_${{env.VERSION}}.tgz v8_9.4 && cd -
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: V8_${{env.VERSION}}_${{ github.event.inputs.tag_date }}
          release_name: V8_${{env.VERSION}}_${{ github.event.inputs.tag_date }}
          draft: false
          prerelease: false
          
      - name: Upload V8
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./v8_bin_${{env.VERSION}}.tgz
          asset_name: v8_bin_${{env.VERSION}}.tgz
          asset_content_type: application/tgz
          

